config/routes.rb
Rails.application.routes.draw do
  root to: 'splash_page#index'
  get '/home', to: 'home#index', as: :home
  get 'splash_page/index', to: 'splash_page#index'

  resources :reservations do
    post 'unfulfilled_send_email'
  end
  resources :locations
  resources :users
  get 'stores/settings'
  get 'stores/activate'
  get 'stores/reinstall'
  get 'stores/resync'
  get 'stores/deactivate'
  get 'stores/setup'
  get 'stores/help'
  get 'stores/templates'
  get 'stores/webhooks'
  match 'stores/settings' => 'stores#save_settings', via: [:post, :patch]

  get 'shopify/recurring_application_charge/create' => 'shopify/recurring_application_charge#create', as: :subscribe
  get 'shopify/recurring_application_charge/callback' => 'shopify/recurring_application_charge#callback', as: :recurring_application_charge_callback

  get '/iframe_preview', to: 'iframe_preview#index', as: :iframe_preview

  namespace :api do
    namespace :v1 do
      get 'locations/modal' => 'locations#modal'
      match 'locations/modal' => 'locations#modal', via: [:post, :get]

      get 'locations' => 'locations#index'
      match 'reservations/modal' => 'reservations#modal', via: [:post, :get]
      get 'inventory' => 'inventory#show'
      get 'inventories' => 'inventory#index'
      get 'stock' => 'inventory#stock'
      post 'reservations' => 'reservations#create'
      get 'reservations' => 'reservations#index'

      # Legacy endpoints
      post 'store_reservations' => 'reservations#create'
      get 'modal' => 'reservations#modal'
    end
  end

  devise_for :admin, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }, path_names: {
    sign_in: 'login', sign_out: 'logout'
  }

  scope :admin, module: :admins, as: :admin do
    root :to => 'stores#index'
    resources :stores do
      get 'show'
      get 'tools'
      get 'reintegrate'
      get 'reservations'
      get 'settings'
      get 'activate'
      get 'templates'
      get 'deactivate'
      get 'locations'
      get 'webhooks'
      get 'reservations'
      match 'admin/stores/settings' => 'stores#save_settings', via: [:post, :patch]
    end
    resources :users
    resources :plans
    resources :uninstallations
    get 'stores/:store_id/subscriptions' => 'subscriptions#index', as: :subscriptions_store
    match 'stores/extend_trial' => 'stores#extend_trial', via: [:post, :patch]
    match 'stores/override_subscriptions' => 'stores#override_subscriptions', via: [:post, :patch]
    match 'stores/notes' => 'stores#save_notes', via: [:post, :patch]
  end

  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/topnavbar/_menu.html.erb
<% unless hide_menu? %>
  <!-- top navigation bar -->
  <div class="Polaris-Card top_navbar">
    <ul role="tablist" class="Polaris-Tabs">
      <li role="presentation" class="Polaris-Tabs__TabContainer">
        <a class="Polaris-Tabs__Tab <%= 'Polaris-Tabs__Tab--selected' if (params[:controller] == 'stores' && params[:action] == 'settings') %>" href="<%= stores_settings_path(view: 'settings', shop: @current_shopify_session.domain) %>">
          <span class="Polaris-Tabs__Title">Settings</span></a>
      </li>
      <li role="presentation" class="Polaris-Tabs__TabContainer">
        <a class="nav-item nav-link Polaris-Tabs__Tab <%= 'Polaris-Tabs__Tab--selected' if (params[:controller] == 'reservations') %>" href="<%= reservations_path %>">
          <span class="Polaris-Tabs__Title">Reservations</span></a>
      </li>
      <li role="presentation" class="Polaris-Tabs__TabContainer">
        <a class="nav-item nav-link Polaris-Tabs__Tab <%= 'Polaris-Tabs__Tab--selected' if (params[:controller] == 'locations') %>" href="<%= locations_path %>">
          <span class="Polaris-Tabs__Title">Locations</span></a>
      </li>
      <li role="presentation" class="Polaris-Tabs__TabContainer">
        <a class="nav-item nav-link Polaris-Tabs__Tab <%= 'Polaris-Tabs__Tab--selected' if (params[:controller] == 'stores' && params[:action] == 'templates') %>" href="<%= stores_templates_path %>">
          <span class="Polaris-Tabs__Title">Templates</span></a>
      </li>
      <% if @current_store.webhooks_enabled? %>
        <li role="presentation" class="Polaris-Tabs__TabContainer">
          <a class="nav-item nav-link Polaris-Tabs__Tab <%= 'Polaris-Tabs__Tab--selected' if (params[:controller] == 'stores' && params[:action] == 'webhooks') %>" href="<%= stores_webhooks_path %>">
            <span class="Polaris-Tabs__Title">Webhooks</span></a>
        </li>
      <% end %>
      <li role="presentation" class="Polaris-Tabs__TabContainer">
        <a class="nav-item nav-link Polaris-Tabs__Tab <%= 'Polaris-Tabs__Tab--selected' if (params[:controller] == 'stores' && params[:action] == 'help') %>" href="<%= stores_help_path %>">
          <span class="Polaris-Tabs__Title">Help</span></a>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/partials/topnavbar/_user_menu.html.erb
  
  <li class="dropdown">
    <a href="#"
       data-toggle="dropdown" role="button" aria-haspopup="false"
       aria-expanded="false"
       class="nav-link dropdown-toggle user-menu-link">
      <i class="fad mr-2 fa-user-cog"></i>
    </a>
    <div class="dropdown-menu dropdown-menu--compact dropdown-menu-right">
      <h6 class="dropdown-header">User</h6>
      <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
      
      <a href="<%= main_app.destroy_admin_session_path %>"  class="dropdown-item">
        <i class="fad mr-2 fa-power-off"></i>
        <span>Log-out</span>
      </a>
    </div>
  </li>