config/routes.rb
Rails.application.routes.draw do
  root to: 'splash_page#index'
  get '/home', to: 'home#index', as: :home
  get 'splash_page/index', to: 'splash_page#index'

  resources :reservations do
    post 'unfulfilled_send_email'
  end
  resources :locations
  resources :users
  get 'stores/settings'
  get 'stores/activate'
  get 'stores/reinstall'
  get 'stores/resync'
  get 'stores/deactivate'
  get 'stores/setup'
  get 'stores/help'
  get 'stores/templates'
  get 'stores/webhooks'
  match 'stores/settings' => 'stores#save_settings', via: [:post, :patch]

  get 'shopify/recurring_application_charge/create' => 'shopify/recurring_application_charge#create', as: :subscribe
  get 'shopify/recurring_application_charge/callback' => 'shopify/recurring_application_charge#callback', as: :recurring_application_charge_callback

  get '/iframe_preview', to: 'iframe_preview#index', as: :iframe_preview

  namespace :api do
    namespace :v1 do
      get 'locations/modal' => 'locations#modal'
      match 'locations/modal' => 'locations#modal', via: [:post, :get]

      get 'locations' => 'locations#index'
      match 'reservations/modal' => 'reservations#modal', via: [:post, :get]
      get 'inventory' => 'inventory#show'
      get 'inventories' => 'inventory#index'
      get 'stock' => 'inventory#stock'
      post 'reservations' => 'reservations#create'
      get 'reservations' => 'reservations#index'

      # Legacy endpoints
      post 'store_reservations' => 'reservations#create'
      get 'modal' => 'reservations#modal'
    end
  end

  devise_for :admin, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }, path_names: {
    sign_in: 'login', sign_out: 'logout'
  }

  scope :admin, module: :admins, as: :admin do
    root :to => 'stores#index'
    resources :stores do
      get 'show'
      get 'tools'
      get 'reintegrate'
      get 'reservations'
      get 'settings'
      get 'activate'
      get 'templates'
      get 'deactivate'
      get 'locations'
      get 'webhooks'
      get 'reservations'
      match 'admin/stores/settings' => 'stores#save_settings', via: [:post, :patch]
    end
    resources :users
    resources :plans
    resources :uninstallations
    get 'stores/:store_id/subscriptions' => 'subscriptions#index', as: :subscriptions_store
    match 'stores/extend_trial' => 'stores#extend_trial', via: [:post, :patch]
    match 'stores/override_subscriptions' => 'stores#override_subscriptions', via: [:post, :patch]
    match 'stores/notes' => 'stores#save_notes', via: [:post, :patch]
  end

  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admins/stores_controller.rb
module Admins
  class StoresController < ::Admins::ApplicationController
    before_action :load_store, except: [:index]
    helper_method :store

    def index
      @stores = Store.order(created_at: :desc)
      @stores = @stores.eager_load(:subscription).page(params[:page]).per(20)
    end

    ##
    # GET /admin/stores/:store_id/show
    def show
      @user = User.where(store_id: params[:store_id].to_i)
    end
    
    ##
    # GET /admin/stores/:store_id/deactivate
    def deactivate
      @store.deactivate!
      
      redirect_to admin_store_tools_path(@store), notice: 'Reserve In-store has been deactivated.'
    end

    ##
    # GET /admin/stores/:store_id/activate
    def activate
      @store.activate!
      
      redirect_to admin_store_tools_path(@store), notice: 'Reserve In-store has been activated.'
    end
    
    ##
    # GET /admin/stores/:store_id/tools
    def tools
    end

    ##
    # GET /admin/stores/:store_id/webhooks
    def webhooks
    end
    
    ##
    # GET /admin/stores/:store_id/reintegrate
    def reintegrate
      UpdateFooterJob.new.perform(@store.id)
      
      redirect_to admin_store_tools_path(@store), notice: 'Reserve In-store has been re-installed into this store.'
    end

    ##
    # GET /admin/stores/:store_id/settings
    def settings
      @locations = @store.locations
    end
    
    ##
    # PUT/PATCH /stores/settings
    def save_settings
      @current_store = @store
      respond_to do |format|
        save_params = store_params

        # Ensure values are boolean if they are enabled/disabled flags
        store_params.keys.each do |key|
          if key.to_s =~ /.+(_enabled)/
            unless store_params[key].is_a?(TrueClass) || store_params[key].is_a?(FalseClass)
              store_params[key] = store_params[key].to_bool
            end
          end
        end

        @current_store.assign_attributes(save_params)

        if @current_store.save
          format.html { redirect_to params[:next_url].presence || stores_settings_url, notice: 'Store settings were successfully updated.' }
          format.json { render :settings, status: :ok }
        else
          format.html { render :settings }
          format.json { render json: @current_store.errors, status: :unprocessable_entity }
        end
      end
    end
    
    ##
    # GET /admin/stores/:store_id/locations
    def locations
       @locations = @store.locations
       @locations = @locations.page(params[:page]).per(20)
    end

    ##
    # GET /admin/stores/:store_id/reservations
    def reservations
       @reservations = @store.reservations
       @reservations = @reservations.page(params[:page]).per(20)
    end
    
    ##
    # GET /admin/stores/:store_id/templates
    def templates
    end

    ##
    # Respond to request with a success if requirement is true and store was saved, or else respond with a fail
    # @param requirement - The requirement that must be satisfied in order to save the store.
    #                    - ex. save_store_and_respond(params[:...].present?), will save as long as the param is present
    #                    - Ensures defensive programming
    def save_store_and_respond(requirement = true)
      respond_to do |format|
        if requirement && @store.save
          format.json { render json: @store.to_json, status: :ok }
        else
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end

    ##
    # PUT/PATCH /admin/stores/override_subscriptions
    def override_subscriptions
      @current_store = @store
      params_exist = params[:overriding].present? && params[:note].present? && params[:user_id].present?

      respond_to do |format|
        if params_exist && @current_store.override_subscriptions!(params[:value], params[:overriding], params[:user_id], params[:note])
          format.json { render json: @current_store.to_json, status: :ok }
        else
          format.json { render json: @current_store.errors, status: :unprocessable_entity }
        end
      end
    end

    ##
    # Make sure that the 4 params that are supposed to be passed into extend_trial were all passed in.
    # Although :email_owner is set to a boolean in trial_updater.js, (and a boolean value returns false on .present? if false)
    # It gets treated as a string on server side, so in this case it returns true on .present? since it's == "false"
    # @returns [Boolean] True if all 4 params are present, false otherwise
    def extend_trial_params_exist?
      params[:length].present? && params[:user_id].present? && params[:note].present? && params[:email_owner].present?
    end

    ##
    # PUT/PATCH /admin/stores/extend_trial
    def extend_trial
      respond_to do |format|
        if extend_trial_params_exist? && @store.extend_trial!(params[:length].to_i, params[:user_id].to_i, params[:note].to_s)
          format.json { render json: @store.to_json, status: :ok }
        else
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end

    ##
    # PUT/PATCH /admin/stores/:store_id/save_notes
    def save_notes
      @store.admin_notes.present? ? @store.admin_notes += "\n" : @store.admin_notes = ""
      @store.admin_notes += "#{Time.now}: #{params[:note]} - #{current_admin.email} (id #{current_admin.id})"
      save_store_and_respond(params[:note].present?)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.fetch(:store, {}).permit(Store::PERMITTED_PARAMS)
    end

    private

    def load_store
      @store = Store.find(params[:store_id].to_i)
    end

    def store; @store; end
  end
end

app/controllers/stores_controller.rb
class StoresController < LoggedInController

  ##
  # GET /stores/help
  def help
    require_user! || return
  end

  ##
  # GET /stores/templates
  def templates
    require_user! || return
  end

  ##
  # GET /stores/setup
  def setup
    if @current_store.users.any?
      redirect_to action: :settings
    end
  end

  ##
  # GET /stores/settings
  def settings
    require_user! || return
  end

  ##
  # GET /stores/webhooks
  def webhooks
  end

  ##
  # GET /stores/deactivate
  def deactivate
    if !@current_store.integrator.footer_script_included? && @current_store.deactivate!
      redirect_to stores_settings_url(view: 'settings'), flash: { notice: "In-Store Reserver app has been deactivated." }
    else
      redirect_to stores_settings_url(view: 'settings', deactivation: "failed")
    end
  end

  ##
  # GET /stores/activate
  def activate
    if @current_store.integrator.snippet_footer_code_found? && @current_store.integrator.footer_script_included?  && @current_store.activate!
      redirect_to stores_settings_url(view: 'settings'), flash: { notice: "In-Store Reserver app has been activated." }
    else
      redirect_to stores_settings_url(view: 'settings', activation: "failed")
    end
  end

  ##
  # GET /stores/reinstall
  def reinstall
    UpdateFooterJob.new.perform(@current_store.id)

    redirect_to stores_settings_url(view: 'settings'), notice: 'Reserve In-store has been re-installed into your store.'
  end
  ##
  # GET /stores/resync
  def resync
    @current_store.sync_locations!

    redirect_to stores_settings_url(view: 'settings'), notice: 'Reserve In-store has re-synced your store locations.'
  end
  ##
  # PUT/PATCH /stores/settings
  def save_settings
    respond_to do |format|
      save_params = store_params

      # Ensure values are boolean if they are enabled/disabled flags
      store_params.keys.each do |key|
        if key.to_s =~ /.+(_enabled)/
          unless store_params[key].is_a?(TrueClass) || store_params[key].is_a?(FalseClass)
            store_params[key] = store_params[key].to_bool
          end
        end
      end

      @current_store.assign_attributes(save_params)

      if @current_store.save
       format.html { redirect_to params[:next_url].presence || stores_settings_url(view: 'settings'), notice: 'Store settings were successfully updated.' }
       format.json { render :settings, status: :ok }
      else
        format.html { redirect_to params[:next_url].presence || stores_settings_url(view: 'settings'), flash: { error: "Store settings was not saved. Please contact our support team for help." }}
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def hide_menu?
    params[:action] == 'setup'
  end

  private

  def require_user!
    unless @current_store.users.any?
      redirect_to(stores_setup_url)
      false
    else
      if !params[:view] && params[:action] != 'templates' && params[:action] != 'help' && params[:action] != 'upgrade' && @current_store.reservations.count > 0
        redirect_to reservations_path(platform_order_id: params[:id])
      end
      true
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def store_params
    params.fetch(:store, {}).permit(Store::PERMITTED_PARAMS)
  end

end

app/helpers/stores_helper.rb
module StoresHelper
  def store_webhooks
    ["reservations/create", "reservations/fulfilled"]
  end

  def default_stock_status_labels
    {
      in_stock: "In Stock",
      low_stock: "Low Stock",
      no_stock: "No Stock",
      stock_unknown: "Stock Unknown"
    }
  end

  def default_stock_status_labels_cart_page
    {
      all_items_available: "All Items Available",
      x_items_available: "X items available",
      no_stock: "No Stock"
    }
  end

  def stock_status_where_to_show
    {
      in_reserve_modal_product_page_locations: "Reserve modal locations (product page)",
      in_reserve_modal_cart_page_locations: "Reserve modal locations (cart page)",
      in_reserve_modal_cart_items: "Reserved product or cart items",
      in_choose_location_modal_product_page: "Choose Location Modal (product page)"
    }
  end

  ##
  # Shopify does not allow us to edit theme due to which we need to provide manual installation footer js script.
  # Used in help article to manually copy and paste code.
  def footer_script_js_code
    StoreIntegrator.new(@current_store).footer_script_code
  end
end

app/views/stores/setup.html.erb
<%= render partial: 'stores/settings/setup' %>

app/views/stores/templates.html.erb
<% if @integrator.present? && @integrator.has_errors? %>
  <div class="Polaris-Banner Polaris-Banner--statusCritical Polaris-Banner--withinPage" tabindex="0" role="alert" aria-live="polite" aria-labelledby="Banner3Heading" aria-describedby="Banner3Content">
    <div class="Polaris-Banner__Ribbon"><span class="Polaris-Icon Polaris-Icon--colorRedDark Polaris-Icon--isColored Polaris-Icon--hasBackdrop"><svg class="Polaris-Icon__Svg" viewBox="0 0 20 20" focusable="false" aria-hidden="true"><g fill-rule="evenodd"><circle fill="currentColor" cx="10" cy="10" r="9"></circle><path d="M2 10c0-1.846.635-3.543 1.688-4.897l11.209 11.209A7.954 7.954 0 0 1 10 18c-4.411 0-8-3.589-8-8m14.312 4.897L5.103 3.688A7.954 7.954 0 0 1 10 2c4.411 0 8 3.589 8 8a7.952 7.952 0 0 1-1.688 4.897M0 10c0 5.514 4.486 10 10 10s10-4.486 10-10S15.514 0 10 0 0 4.486 0 10"></path></g></svg></span></div>
    <div>
      <div class="Polaris-Banner__Heading" id="Banner3Heading">
        <p class="Polaris-Heading">Automatic Theme Integration Failed</p>
      </div>
      <div class="Polaris-Banner__Content" id="Banner3Content">
        <%= @integrator.errors.map{ |error_msg| "<p>#{error_msg}</p>" }.join('').html_safe %>
      </div>
    </div>
  </div>
<% end %>

<% content_for(:title) { 'Templates' } %>

<%= render partial: 'layouts/partials/error_banner', locals: {item: @current_store} %>

<% if @current_store.needs_subscription? ||
  @current_store.needs_upgrade_subscription? && (@current_store.recommended_feature_plan('custom_templates').price > @current_store.subscription.plan.price)
%>
  <%= render partial: 'stores/subscriptions/partials/feature_upgrade_subscription',
             locals: { store: @current_store, feature: 'custom_templates' }
  %>
<% end %>

<% if @current_store.needs_subscription? ||
      @current_store.created_at >  Time.parse('July 23, 2022 EDT') &&
      (@current_store.needs_upgrade_subscription? && (@current_store.recommended_feature_plan('custom_templates').price > @current_store.subscription.plan.price))

     disable_editing = 'disable-editing'
   end
%>

<div class="Polaris-Page templatePage <%= disable_editing || '' %>">
  <div class="Polaris-Page__Content">
    <%= form_with(model: @current_store, url: {action: 'save_settings'}, html: {id: 'store_settings_form'}) do |f| %>
      <input type="hidden" value="<%= stores_templates_url %>" name="next_url">

      <div class="Polaris-Layout">

        <%= render partial: 'stores/shared/liquid_editor_section', locals: {
            heading: 'Reserve Modal',
            subheading: 'Customize the appearance and content of the New Reservation modal.',
            attr: 'reserve_modal_tpl',
            enabled: @current_store.reserve_modal_tpl_enabled?,
            db_value: @current_store.reserve_modal_tpl,
            value_in_use: @current_store.reserve_modal_tpl_in_use,
            default_value: @current_store.default_reserve_modal_tpl,
            preview_vars: @current_store.frontend_tpl_vars.merge({
                  cart: {
                      items: [
                        {
                            product_title: 'Sample Product',
                            variant_title: "Color Blue / Size 3",
                            total: 12.34,
                            total_formatted: @current_store.currency(12.34)
                        }
                      ]
                  }
            }),
            container_css_class: '',
            extra_css: '.reserveInStore-reserve-modal { padding-top: 12px; padding-bottom: 12px; position: relative; top: 8px; } .reserveInStore-reserve-close { top: 5px; }',
            frontend_mode: true
        } %>


        <%= render partial: 'stores/shared/liquid_editor_section', locals: {
            heading: 'Choose Location Modal',
            subheading: 'Customize the content of the Choose Location modal.',
            attr: 'choose_location_modal_tpl',
            enabled: @current_store.choose_location_modal_tpl_enabled?,
            db_value: @current_store.choose_location_modal_tpl,
            value_in_use: @current_store.choose_location_modal_tpl_in_use,
            default_value: @current_store.default_choose_location_modal_tpl,
            preview_vars: @current_store.frontend_tpl_vars,
            container_css_class: '',
            extra_css: '.reserveInStore-reserve-modal { padding-top: 12px; padding-bottom: 12px; position: relative; top: 8px; } .reserveInStore-reserve-close { top: 5px; }',
            frontend_mode: true
        } %>


        <%= render partial: 'stores/shared/email_template_section', locals: {
            heading: 'Reservation Confirmation Email',
            enabled: @current_store.customer_confirm_email_tpl_enabled?,
            subheading: 'Customize the reservation email that gets sent to customers using HTML.',
            attr: 'customer_confirm_email_tpl',
            db_value: @current_store.customer_confirm_email_tpl,
            value_in_use: @current_store.customer_confirm_email_tpl_in_use,
            default_value: @current_store.default_customer_confirm_email_tpl,
            preview_vars: Reservation.new(store: @current_store).preview_email_liquid_params,
            dont_use_global_css: true,
            preview_params: { email: true },
            sender_name_field: :customer_confirmation_sender_name,
            sender_name_field_default: 'Default: Reserve In-store',
            subject_field: :customer_confirmation_subject,
            subject_field_default: 'Default: In-Store Reservation Confirmation',
            f: f
            # container_css_class: 'reserveInStore-reserve-modal',
            # frontend_mode: true
        } %>

        <%= render partial: 'stores/shared/email_template_section', locals: {
            heading: 'Location Notification Email',
            enabled: @current_store.location_notification_email_tpl_enabled?,
            subheading: 'Options for the notification email that gets sent to a store location email address when a new store reservation is created by a visitor.',
            attr: 'location_notification_email_tpl',
            db_value: @current_store.location_notification_email_tpl,
            value_in_use: @current_store.location_notification_email_tpl_in_use,
            default_value: @current_store.default_location_notification_email_tpl,
            preview_vars: Reservation.new(store: @current_store).preview_email_liquid_params,
            dont_use_global_css: true,
            preview_params: { email: true },
            sender_name_field: :location_notification_sender_name,
            sender_name_field_default: 'Default: Reserve In-store',
            subject_field: :location_notification_subject,
            subject_field_default: 'Default: New In-store Reservation',
            f: f
        } %>

        <%= render partial: 'stores/shared/email_template_section', locals: {
            heading: 'Fulfilled Reservation Notification Email',
            enabled: @current_store.fulfilled_reservation_notification_email_tpl_enabled?,
            subheading: 'Customize the reservation status email that gets sent to customers.',
            attr: 'fulfilled_reservation_notification_email_tpl',
            db_value: @current_store.fulfilled_reservation_notification_email_tpl,
            value_in_use: @current_store.fulfilled_reservation_notification_email_tpl_in_use,
            default_value: @current_store.default_fulfilled_reservation_notification_email_tpl,
            preview_vars: Reservation.new(store: @current_store).preview_email_liquid_params,
            dont_use_global_css: true,
            preview_params: { email: true },
            sender_name_field: :fulfilled_reservation_sender_name,
            sender_name_field_default: 'Default: Reserve In-store',
            subject_field: :fulfilled_reservation_subject,
            subject_field_default: 'Default: In-store Reservation Fulfilled',
            f: f
        } %>

        <%= render partial: 'stores/shared/email_template_section', locals: {
            heading: 'Unfulfilled Reservation Notification Email',
            enabled: @current_store.unfulfilled_reservation_notification_email_tpl_enabled?,
            subheading: 'Customize the reservation status email that gets sent to customers.',
            attr: 'unfulfilled_reservation_notification_email_tpl',
            db_value: @current_store.unfulfilled_reservation_notification_email_tpl,
            value_in_use: @current_store.unfulfilled_reservation_notification_email_tpl_in_use,
            default_value: @current_store.default_unfulfilled_reservation_notification_email_tpl,
            preview_vars: Reservation.new(store: @current_store).preview_email_liquid_params,
            dont_use_global_css: true,
            preview_params: { email: true },
            sender_name_field: :unfulfilled_reservation_sender_name,
            sender_name_field_default: 'Default: Reserve In-store',
            subject_field: :unfulfilled_reservation_subject,
            subject_field_default: 'Default: In-store Reservation Unfulfilled',
            f: f
        } %>

        <%= render partial: 'stores/shared/liquid_editor_section', locals: {
            heading: 'Product Page Reserve Button',
            enabled: @current_store.reserve_product_btn_tpl_enabled?,
            subheading: 'Customize the appearance of the "Reserve In-Store" button that appears in the product pages (if it is enabled).',
            attr: 'reserve_product_btn_tpl',
            db_value: @current_store.reserve_product_btn_tpl_in_use,
            value_in_use: @current_store.reserve_product_btn_tpl_in_use,
            default_value: @current_store.default_reserve_product_btn_tpl,
            extra_css: '.reserveInStore-btn-container { margin-top: 0 }',
            frontend_mode: true
        } %>

        <%= render partial: 'stores/shared/liquid_editor_section', locals: {
            heading: 'Cart Reserve Button',
            enabled: @current_store.reserve_cart_btn_tpl_enabled?,
            subheading: 'Customize the appearance of the "Reserve In-Store" button that appears in the cart pages (if it is enabled).',
            attr: 'reserve_cart_btn_tpl',
            db_value: @current_store.reserve_cart_btn_tpl_in_use,
            value_in_use: @current_store.reserve_cart_btn_tpl_in_use,
            default_value: @current_store.default_reserve_cart_btn_tpl,
            extra_css: '.reserveInStore-btn-container { margin-top: 0 }',
            frontend_mode: true
        } %>

        <%= render partial: 'stores/shared/liquid_editor_section', locals: {
            heading: 'Product Page Stock Status Indicator',
            enabled: @current_store.stock_status_tpl_enabled?,
            subheading: 'Customize the appearance of the "in stock @ location" stock status indicator for when it is enabled and active.',
            attr: 'stock_status_tpl',
            db_value: @current_store.stock_status_tpl_in_use,
            value_in_use: @current_store.stock_status_tpl_in_use,
            default_value: @current_store.default_stock_status_tpl,
            # extra_css: '.reserveInStore-btn-container { margin-top: 0 }',
            frontend_mode: true
        } %>

        <%= render partial: 'stores/settings/custom_css', locals: {
            enabled: @current_store.custom_css_enabled?,
            db_value: @current_store.custom_css,
            value_in_use: @current_store.custom_css_in_use,
            default_value: ''
        } %>


        <div class="Polaris-Layout__Section">
          <div class="Polaris-PageActions">
            <div class="Polaris-Stack Polaris-Stack--spacingTight Polaris-Stack--distributionTrailing">
              <div class="Polaris-Stack__Item">
                <button id="submission_button" type="submit" class="Polaris-Button Polaris-Button--primary">
                  <span class="Polaris-Button__Content"><span>Save</span></span></button>
              </div>
            </div>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

<% content_for(:javascript) do %>
  <script>
      var parsleyBinder = new ParsleyBinder({
          btnSelector: '#submission_button',
          formSelector: '#store_settings_form'
      });
  </script>
<% end %>

app/views/stores/webhooks.html.erb
<% content_for(:title) { 'Webhooks' } %>

<div class="Polaris-Page">
  <div class="Polaris-Page__Content">
    <%= form_with(model: @current_store, url: { action: 'save_settings' }, html: { id: 'store_settings_form' }) do |f| %>
      <input type="hidden" value="<%= stores_webhooks_url %>" name="next_url">

      <div class="Polaris-Layout">
        <div class="Polaris-Layout__AnnotatedSection">
          <div class="Polaris-Layout__AnnotationWrapper">
            <div class="Polaris-Layout__Annotation">
              <div class="Polaris-TextContainer">
                <h2 class="Polaris-Heading">Webhooks</h2>
                <p>Webhooks allow you to react on your own servers whenever an event occurs on the Reserve In-store servers.</p>
              </div>
            </div>
            <div class="Polaris-Layout__AnnotationContent">
              <div class="Polaris-Card">
                <div class="Polaris-Card__Section">
                  <div class="Polaris-FormLayout">
                    <% @current_store.webhooks.each do |hook| %>
                      <div class="Polaris-FormLayout__Item">
                        <div class="Polaris-Label">
                          <label class="Polaris-Label__Text">Endpoint</label>
                        </div>
                        <div class="Polaris-TextField">
                          <input type="text" name="store[webhooks][][url]" class="Polaris-TextField__Input" value="<%= hook['url'] %>" />
                          <div class="Polaris-TextField__Backdrop"></div>
                        </div>
                      </div>

                      <div class="Polaris-FormLayout__Item">
                        <div class="Polaris-Label">
                          <label class="Polaris-Label__Text">Auth Token</label>
                        </div>
                        <div class="Polaris-TextField">
                          <input type="text" name="store[webhooks][][auth_token]" class="Polaris-TextField__Input" value="<%= hook['auth_token'] %>" />
                          <div class="Polaris-TextField__Backdrop"></div>
                        </div>
                      </div>

                      <div class="Polaris-FormLayout__Item">
                        <div class="Polaris-Labelled__LabelWrapper">
                          <div class="Polaris-Label">
                            <%= f.label "Topic", class: "Polaris-Label__Text"%>
                          </div>
                        </div>

                        <fieldset class="Polaris-ChoiceList">
                          <ul class="Polaris-ChoiceList__Choices">
                            <% store_webhooks.each do |topic| %>
                              <% default_checked = hook["topic"].include?(topic.to_s) rescue false %>
                              <li>
                                <label class="Polaris-Choice" for="store_webhooks_<%= topic %>">
                                  <div class="Polaris-Choice__Control">
                                    <div class="Polaris-Checkbox">
                                      <%= check_box_tag "store[webhooks][][topic][]", topic, default_checked,
                                                        class: "Polaris-Checkbox__Input", id: "store_webhooks_#{topic}" %>
                                      <div class="Polaris-Checkbox__Backdrop"></div>
                                      <div class="Polaris-Checkbox__Icon">
                                        <span class="Polaris-Icon">
                                          <svg class="Polaris-Icon__Svg" viewBox="0 0 20 20">
                                            <g fill-rule="evenodd">
                                              <path d="M8.315 13.859l-3.182-3.417a.506.506 0 0 1 0-.684l.643-.683a.437.437 0 0 1 .642 0l2.22 2.393 4.942-5.327a.437.437 0 0 1 .643 0l.643.684a.504.504 0 0 1 0 .683l-5.91 6.35a.437.437 0 0 1-.642 0"></path>
                                            </g>
                                          </svg>
                                        </span>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="Polaris-Choice__Label"><%= topic %></div>
                                </label>
                              </li>
                            <% end %>
                          </ul>
                        </fieldset>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

            <div class="Polaris-Layout__Section">
              <div class="Polaris-PageActions">
                <div class="Polaris-Stack Polaris-Stack--spacingTight Polaris-Stack--distributionTrailing">
                  <div class="Polaris-Stack__Item">
                    <button id="submission_button" type="submit" class="Polaris-Button Polaris-Button--primary">
                      <span class="Polaris-Button__Content"><span>Save</span></span></button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>