config/routes.rb
Rails.application.routes.draw do
  root to: 'splash_page#index'
  get '/home', to: 'home#index', as: :home
  get 'splash_page/index', to: 'splash_page#index'

  resources :reservations do
    post 'unfulfilled_send_email'
  end
  resources :locations
  resources :users
  get 'stores/settings'
  get 'stores/activate'
  get 'stores/reinstall'
  get 'stores/resync'
  get 'stores/deactivate'
  get 'stores/setup'
  get 'stores/help'
  get 'stores/templates'
  get 'stores/webhooks'
  match 'stores/settings' => 'stores#save_settings', via: [:post, :patch]

  get 'shopify/recurring_application_charge/create' => 'shopify/recurring_application_charge#create', as: :subscribe
  get 'shopify/recurring_application_charge/callback' => 'shopify/recurring_application_charge#callback', as: :recurring_application_charge_callback

  get '/iframe_preview', to: 'iframe_preview#index', as: :iframe_preview

  namespace :api do
    namespace :v1 do
      get 'locations/modal' => 'locations#modal'
      match 'locations/modal' => 'locations#modal', via: [:post, :get]

      get 'locations' => 'locations#index'
      match 'reservations/modal' => 'reservations#modal', via: [:post, :get]
      get 'inventory' => 'inventory#show'
      get 'inventories' => 'inventory#index'
      get 'stock' => 'inventory#stock'
      post 'reservations' => 'reservations#create'
      get 'reservations' => 'reservations#index'

      # Legacy endpoints
      post 'store_reservations' => 'reservations#create'
      get 'modal' => 'reservations#modal'
    end
  end

  devise_for :admin, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }, path_names: {
    sign_in: 'login', sign_out: 'logout'
  }

  scope :admin, module: :admins, as: :admin do
    root :to => 'stores#index'
    resources :stores do
      get 'show'
      get 'tools'
      get 'reintegrate'
      get 'reservations'
      get 'settings'
      get 'activate'
      get 'templates'
      get 'deactivate'
      get 'locations'
      get 'webhooks'
      get 'reservations'
      match 'admin/stores/settings' => 'stores#save_settings', via: [:post, :patch]
    end
    resources :users
    resources :plans
    resources :uninstallations
    get 'stores/:store_id/subscriptions' => 'subscriptions#index', as: :subscriptions_store
    match 'stores/extend_trial' => 'stores#extend_trial', via: [:post, :patch]
    match 'stores/override_subscriptions' => 'stores#override_subscriptions', via: [:post, :patch]
    match 'stores/notes' => 'stores#save_notes', via: [:post, :patch]
  end

  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :store
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < ::Admins::ApplicationController

    def index
      @users = User.order(created_at: :desc)
      if params[:query]
        @users = load_users_from_search_query(params[:query])
      end

      @users = @users.page(params[:page]).per(20)
    end
    
    private

    def load_users_from_search_query(query)
      if params[:query].to_s.downcase.strip =~ /^pk_.+$/
        matched_store_ids = Store.where(public_key: params[:query].to_s.downcase.strip).pluck(:id).to_a
      elsif params[:query].to_s.strip =~ /^sk_.+$/
        matched_store_ids = Store.where(secret_key: params[:query].to_s.downcase.strip).pluck(:id).to_a
      else
        query_str = query.to_s.strip.downcase
        matched_store_ids = []
        matched_store_ids += Store.where('LOWER(shopify_domain) LIKE :query OR LOWER(name) LIKE :query', query: "%#{query_str}%").pluck(:id).to_a
        matched_store_ids += User.where('LOWER(email) LIKE :query OR LOWER(name) LIKE :query', query: "%#{query_str}%").pluck(:store_id).to_a
      end

      @users.where(store_id: matched_store_ids.to_a.uniq)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < LoggedInController

  ##
  # POST /users
  def create
    user = User.new(params.fetch(:user, {}).permit(:name, :email).merge(store: @current_store))

    if user.save
      redirect_to stores_settings_url
    else
      ForcedLogger.log(user.errors.inspect)
      redirect_to stores_setup_url, flash: { error: "A problem occurred with your signup details. Please contact our support team for help."}
    end
  end

  def hide_menu?
    params[:action] == 'setup'
  end

end

app/views/admins/users/index.html.erb
<div class="content-heading page-title ">
  <div class="content-heading-row align-items-center justify-content-center">
    <div class="content-heading-left">
        <h1>Users</h1>
    </div>
  </div>
</div>

<div class="row mb-3">
  <div class="col">
    Showing <%= pluralize(@users.total_count, 'users') %>
  </div>
</div>

<div class="card">
  <div class="card-body">
  <div class=" table-responsive">
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Created</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= local_time(user.created_at) %><br>
            (<%= time_ago_in_words(user.created_at) %> ago)</td>
          <td><a href="<%= admin_store_show_path(user.store_id) %>" class="btn btn-secondary btn-sm">View Store</a></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @users %>
  </div>
</div>