config/routes.rb
Rails.application.routes.draw do
  root to: 'splash_page#index'
  get '/home', to: 'home#index', as: :home
  get 'splash_page/index', to: 'splash_page#index'

  resources :reservations do
    post 'unfulfilled_send_email'
  end
  resources :locations
  resources :users
  get 'stores/settings'
  get 'stores/activate'
  get 'stores/reinstall'
  get 'stores/resync'
  get 'stores/deactivate'
  get 'stores/setup'
  get 'stores/help'
  get 'stores/templates'
  get 'stores/webhooks'
  match 'stores/settings' => 'stores#save_settings', via: [:post, :patch]

  get 'shopify/recurring_application_charge/create' => 'shopify/recurring_application_charge#create', as: :subscribe
  get 'shopify/recurring_application_charge/callback' => 'shopify/recurring_application_charge#callback', as: :recurring_application_charge_callback

  get '/iframe_preview', to: 'iframe_preview#index', as: :iframe_preview

  namespace :api do
    namespace :v1 do
      get 'locations/modal' => 'locations#modal'
      match 'locations/modal' => 'locations#modal', via: [:post, :get]

      get 'locations' => 'locations#index'
      match 'reservations/modal' => 'reservations#modal', via: [:post, :get]
      get 'inventory' => 'inventory#show'
      get 'inventories' => 'inventory#index'
      get 'stock' => 'inventory#stock'
      post 'reservations' => 'reservations#create'
      get 'reservations' => 'reservations#index'

      # Legacy endpoints
      post 'store_reservations' => 'reservations#create'
      get 'modal' => 'reservations#modal'
    end
  end

  devise_for :admin, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }, path_names: {
    sign_in: 'login', sign_out: 'logout'
  }

  scope :admin, module: :admins, as: :admin do
    root :to => 'stores#index'
    resources :stores do
      get 'show'
      get 'tools'
      get 'reintegrate'
      get 'reservations'
      get 'settings'
      get 'activate'
      get 'templates'
      get 'deactivate'
      get 'locations'
      get 'webhooks'
      get 'reservations'
      match 'admin/stores/settings' => 'stores#save_settings', via: [:post, :patch]
    end
    resources :users
    resources :plans
    resources :uninstallations
    get 'stores/:store_id/subscriptions' => 'subscriptions#index', as: :subscriptions_store
    match 'stores/extend_trial' => 'stores#extend_trial', via: [:post, :patch]
    match 'stores/override_subscriptions' => 'stores#override_subscriptions', via: [:post, :patch]
    match 'stores/notes' => 'stores#save_notes', via: [:post, :patch]
  end

  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :store

  delegate :price, :code, :name, :features, :limits, :trial_days, to: :plan

  scope :total_active_mrr, -> {
    where(store_id: Store.all.find_all{ |s| s.connected? && (s.trial_days_left || 0) < 1 }.map{ |s| s.id }).sum("(plan_attributes ->> 'price')::float")
  }

  ##
  # @return [Plan] A READONLY Plan based on the stored data from the plan when this subscription was created.
  def plan
    return @plan if @plan.present?

    @plan = Plan.new
    @plan.attributes.keys.each do |k|
      plan_attribute_val = plan_attributes.to_h.with_indifferent_access[k]
      next unless plan_attribute_val.present?

      @plan.send("#{k}=", plan_attribute_val)
    end

    @plan
  end

  ##
  # Assigns the plan ID and plan attributes values to this subscription.
  # Later calling #plan will return a readonly object that contains these attributes.
  # @note Make sure the subscription.store already exists before running this line or else the per location pricing may not work properly.
  # @param plan [Plan] Plan model to use in creating the subscription.
  def plan=(plan)
    plan_attr = plan.attributes

    plan_attr['limits'] ||= {}

    if store.present?
      plan_attr['price'] = plan.price_for_store(store)
      plan_attr['limits']['locations'] = store.distinctly_named_location_count
    end

    plan_attr['limits'] = plan_attr['limits'].merge(store.plan_overrides.to_h['limits'].to_h)

    self.plan_attributes = plan_attr

    @plan = nil # To force the #plan method to reload

    self
  end

  ##
  # @param currency [String|Symbol] What currency should the price be in? Defaults to USD
  # @param round: [Boolean] If true the number will be rounded to the nearest whole number
  # @return [String] Price of the subscription per month
  def nice_price(currency = :usd, round: true)
    converted_price = Bananastand::CurrencyConverter.convert(price, to: currency)
    converted_price = converted_price.round if round
    ActionController::Base.helpers.number_to_currency(converted_price).to_s.chomp('.00').chomp('.00') + "/mo"
  end
end

app/controllers/admins/subscriptions_controller.rb
module Admins
  class SubscriptionsController < ::Admins::ApplicationController
    before_action :load_store_for_admin

    ##
    # GET /admin/stores/:store_id/subscriptions
    def index
      @subscription = @store.subscription
    end

    private

    def load_store_for_admin
      @store = Store.find(params[:store_id].to_i)
    end
  end
end

app/views/stores/subscriptions/partials/_custom_subscription.html.erb
<% if store.custom_fixed_price < store.subscription.plan.price %>
  <div class="Polaris-Layout__Section Polaris-Banner Polaris-Banner--statusWarning Polaris-Banner--withinPage subscription-banner">
    <div class="Polaris-Banner__Ribbon">
      <span class="Polaris-Icon Polaris-Icon--colorYellowDark Polaris-Icon--isColored Polaris-Icon--hasBackdrop">
        <svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
          <circle fill="currentColor" cx="10" cy="10" r="9"></circle>
          <path d="M10 0C4.486 0 0 4.486 0 10s4.486 10 10 10 10-4.486 10-10S15.514 0 10 0m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8m0-13a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0V6a1 1 0 0 0-1-1m0 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2"></path>
        </svg>
      </span>
    </div>
    <div class="Polaris-Banner__ContentWrapper">
      <div class="Polaris-Banner__Heading">
        <div class="Polaris-Heading">Subscribe to Custom Discount Plan</div>
      </div>
      <div class="Polaris-Banner__Content">

        <div class="details">
          <p>Current Subscription: $<%= store.subscription.plan.price.to_s.chomp('.00').chomp('.0') %> <sup>/mo</sup></p>
          <p>Custom Subscription: $<%= store.custom_fixed_price %> <sup>/mo</sup></p>
          <p>Save: $<%= store.subscription.plan.price - store.custom_fixed_price %> <sup>/mo</sup></p>
          <p>&nbsp;</p>
        </div>
        <div class="Polaris-Banner__Actions">
          <div class="Polaris-ButtonGroup">
            <div class="Polaris-ButtonGroup__Item">
              <div class="Polaris-Banner__PrimaryAction">
                <a href="#" class="Polaris-Button Polaris-Button--outline btn-subscribe">
                  Subscribe now
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% content_for(:javascript) do %>
  <script>
      var subscriptionRedirect = new SubscriptionRedirect({
          btnSelector: ".btn-subscribe",
          subscriptionPath: "<%= subscribe_path(plan: @current_store.recommended_plan.code, shop: @current_store.shopify_domain) %>"
      });
  </script>
<% end %>

app/views/stores/subscriptions/partials/_feature_upgrade_subscription.html.erb
  <div class="Polaris-Layout__Section Polaris-Banner Polaris-Banner--statusInfo Polaris-Banner--withinPage subscription-banner">
    <div class="Polaris-Banner__Ribbon">
      <span class="Polaris-Icon Polaris-Icon--colorTealDark Polaris-Icon--isColored Polaris-Icon--hasBackdrop">
        <svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
          <circle fill="currentColor" cx="10" cy="10" r="9"></circle>
          <path d="M10 0C4.486 0 0 4.486 0 10s4.486 10 10 10 10-4.486 10-10S15.514 0 10 0m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8m0-13a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0V6a1 1 0 0 0-1-1m0 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2"></path>
        </svg>
      </span>
    </div>
    <div >

      <div class="Polaris-Banner__Content feature-info">
        <div>This feature is only available in
          <span class="Polaris-TextStyle--variationStrong"><%= store.recommended_feature_plan_code(local_assigns[:feature]) %></span>
          <span class="Polaris-TextStyle--variationStrong">($<%= store.recommended_feature_plan(local_assigns[:feature]).price.to_s.chomp('.00').chomp('.0') %> <sup>/mo</sup>)</span>
           and above
          plans. If you have any questions please contact our support team.</div>

        <% if store.needs_subscription? ||
          store.needs_upgrade_subscription? && (store.recommended_feature_plan(local_assigns[:feature]).price > store.subscription.plan.price)
        %>
          <div class="Polaris-Banner__Actions">
            <div class="Polaris-ButtonGroup">
              <div class="Polaris-ButtonGroup__Item">
                <div class="Polaris-Banner__PrimaryAction">
                  <a href="#" class="Polaris-Button Polaris-Button--outline btn-feature-subscribe">
                  Upgrade now
                  </a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% content_for(:javascript) do %>
    <script>
        var subscriptionRedirect = new SubscriptionRedirect({
            btnSelector: ".btn-feature-subscribe",
            subscriptionPath: "<%= subscribe_path(plan: store.recommended_feature_plan_code(local_assigns[:feature]), post_subscribe_url: stores_settings_url(action: 'upgrade')) %>"
        });
    </script>
  <% end %>

app/views/stores/subscriptions/partials/_need_subscription.html.erb
<% if store.trial_ends_at > Time.now %>
  <div class="Polaris-Layout__Section Polaris-Banner Polaris-Banner--statusWarning Polaris-Banner--withinPage">
    <div class="Polaris-Banner__Ribbon">
      <span class="Polaris-Icon Polaris-Icon--colorYellowDark Polaris-Icon--isColored Polaris-Icon--hasBackdrop">
        <svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
          <circle fill="currentColor" cx="10" cy="10" r="9"></circle>
          <path d="M10 0C4.486 0 0 4.486 0 10s4.486 10 10 10 10-4.486 10-10S15.514 0 10 0m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8m0-13a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0V6a1 1 0 0 0-1-1m0 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2"></path>
        </svg>
      </span>
    </div>
    <div class="Polaris-Banner__ContentWrapper">
      <div class="Polaris-Banner__Heading">
        <div class="Polaris-Heading">You are not subscribed to a plan yet.</div>
      </div>
      <div class="Polaris-Banner__Content">
         You have <span class="Polaris-TextStyle--variationStrong"><%= time_ago_in_words(store.trial_ends_at) %></span> left of your unlimited-use trial period.
        <div class="Polaris-Banner__Actions">
          <div class="Polaris-ButtonGroup">
            <div class="Polaris-ButtonGroup__Item">
              <div class="Polaris-Banner__PrimaryAction">
                <a href="#" class="Polaris-Button Polaris-Button--outline btn-subscribe">
                  Subscribe Now
                </a>
              </div>
            </div>
          </div>
        </div>
        <p class="subscription-note">
          <span class="Polaris-TextStyle--variationStrong">Note:</span> You'll still get your free trial days if you subscribe now and you won't be billed anything until the trial is over.
        </p>
      </div>
    </div>
  </div>
<% else %>
  <div class="Polaris-Layout__Section Polaris-Banner Polaris-Banner--statusCritical Polaris-Banner--withinPage">
    <div class="Polaris-Banner__Ribbon">
      <span class="Polaris-Icon Polaris-Icon--colorRedDark Polaris-Icon--isColored Polaris-Icon--hasBackdrop">
        <svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
          <circle fill="currentColor" cx="10" cy="10" r="9"></circle>
          <path d="M10 0C4.486 0 0 4.486 0 10s4.486 10 10 10 10-4.486 10-10S15.514 0 10 0m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8m0-13a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0V6a1 1 0 0 0-1-1m0 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2"></path>
        </svg>
      </span>
    </div>
    <div class="Polaris-Banner__ContentWrapper">
      <div class="Polaris-Banner__Heading">
        <div class="Polaris-Heading">You are not subscribed to a plan yet.</div>
      </div>
      <div class="Polaris-Banner__Content">
         Trial expired <span class="Polaris-TextStyle--variationStrong"><%= time_ago_in_words(store.trial_ends_at) %></span> ago.
         Please subscribe to a plan by clicking subscribe link to continue. If you have any questions/concerns/comments please contact our support team.

        <div class="Polaris-Banner__Actions">
          <div class="Polaris-ButtonGroup">
            <div class="Polaris-ButtonGroup__Item">
              <div class="Polaris-Banner__PrimaryAction">
                <a href="#" class="Polaris-Button Polaris-Button--outline btn-subscribe" target="_blank">
                  Subscribe Now
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% content_for(:javascript) do %>
  <script>
      var subscriptionRedirect = new SubscriptionRedirect({
          btnSelector: ".btn-subscribe",
          subscriptionPath: "<%= subscribe_path(plan: @current_store.recommended_plan.code, shop: @current_store.shopify_domain) %>"
      });
  </script>
<% end %>

app/views/stores/subscriptions/partials/_upgrade_subscription.html.erb
<% if store.recommended_plan.price > store.subscription.plan.price %>
  <div class="Polaris-Layout__Section Polaris-Banner Polaris-Banner--statusWarning Polaris-Banner--withinPage subscription-banner">
    <div class="Polaris-Banner__Ribbon">
      <span class="Polaris-Icon Polaris-Icon--colorYellowDark Polaris-Icon--isColored Polaris-Icon--hasBackdrop">
        <svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
          <circle fill="currentColor" cx="10" cy="10" r="9"></circle>
          <path d="M10 0C4.486 0 0 4.486 0 10s4.486 10 10 10 10-4.486 10-10S15.514 0 10 0m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8m0-13a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0V6a1 1 0 0 0-1-1m0 8a1 1 0 1 0 0 2 1 1 0 0 0 0-2"></path>
        </svg>
      </span>
    </div>
    <div class="Polaris-Banner__ContentWrapper">
      <div class="Polaris-Banner__Heading">
        <div class="Polaris-Heading">Subscribed to <%= store.subscription.plan.name %> Plan</div>
      </div>
      <div class="Polaris-Banner__Content">
        You've exceeded the maximum number of locations for your current plan (Limit: <%= store.subscription.plan.limits["locations"] %>). Please upgrade your plan to continue.
        If you have any questions/concerns/comments please contact our support team.
        <div class="details">There are <%= store.distinctly_named_location_count %> active locations in your store. </div>
        <div class="Polaris-Banner__Actions">
          <div class="Polaris-ButtonGroup">
            <div class="Polaris-ButtonGroup__Item">
              <div class="Polaris-Banner__PrimaryAction">
                <a href="#" class="Polaris-Button Polaris-Button--outline btn-subscribe">
                  Upgrade Plan
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% content_for(:javascript) do %>
  <script>
      var subscriptionRedirect = new SubscriptionRedirect({
          btnSelector: ".btn-subscribe",
          subscriptionPath: "<%= subscribe_path(plan: @current_store.recommended_plan.code, shop: @current_store.shopify_domain) %>"
      });
  </script>
<% end %>